/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        indigo: {
          50: '#eef4fc',
          100: '#d6e6fa',
          500: '#2b7fde',
          600: '#1669d3',
          700: '#114f9e',
        },
        accent: { DEFAULT: '#1669D3', tint: '#E6F0FC', grip: '#9DC2ED' },
        line: { DEFAULT: '#E6E6EC', dashed: '#D8D8E2' },
        ink: { DEFAULT: '#1B1B22', muted: '#8D8D97', faint: '#B7B7C1' },
        warn: '#F5A623',
        success: '#2FAE66',
        canvas: { DEFAULT: '#F4F4F7', track: '#EDEDF2' },
        desktop: {
          sidebar: '#1c1533',
          primary: '#1669d3',
          gradFrom: '#3e8ee8',
          gradTo: '#114f9e',
          content: '#f6f5fb',
          card: '#ffffff',
          cardBorder: '#e7e4f3',
          divider: '#f1effa',
          text: '#181225',
          textSecondary: '#4d4761',
          textMuted: '#726d85',
          textMuted2: '#8b85a0',
          textMuted3: '#9891ac',
          placeholder: '#b3aec3',
          tileHome: '#dcebfb',
          tileQuick: '#dce9fa',
          tileAccent: '#e7f0fc',
          successText: '#1a8f5c',
          successText2: '#1fa971',
          successBg: '#e9f7ef',
          chipBg: '#e9f1fc',
        },
      },
      fontFamily: {
        desktop: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
