/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        indigo: {
          50: '#eef2ff',
          100: '#e0e7ff',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
        },
        accent: { DEFAULT: '#6C5CE7', tint: '#EEEAFC', grip: '#C7BFF2' },
        line: { DEFAULT: '#E6E6EC', dashed: '#D8D8E2' },
        ink: { DEFAULT: '#1B1B22', muted: '#8D8D97', faint: '#B7B7C1' },
        warn: '#F5A623',
        success: '#2FAE66',
        canvas: { DEFAULT: '#F4F4F7', track: '#EDEDF2' },
        desktop: {
          sidebar: '#1c1533',
          primary: '#5140d6',
          gradFrom: '#8b7bff',
          gradTo: '#5a4bd6',
          content: '#f6f5fb',
          card: '#ffffff',
          cardBorder: '#e7e4f3',
          divider: '#f1effa',
          text: '#181225',
          textSecondary: '#4d4761',
          textMuted: '#726d85',
          textMuted2: '#8b85a0',
          textMuted3: '#9891ac',
          placeholder: '#b3aec3',
          tileHome: '#e4e0fa',
          tileQuick: '#f5e4fa',
          tileAccent: '#efecfb',
          successText: '#1a8f5c',
          successText2: '#1fa971',
          successBg: '#e9f7ef',
          chipBg: '#f1effa',
        },
      },
      fontFamily: {
        desktop: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
